Repository MznAarik/final_project, pull requests merged in 2025-08, with the labels that each got.

#47 feat: Update AdminController to include admin dashboard functionality…
  .env.example
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/TicketController.php
  resources/views/admin/dashboard.blade.php
  resources/views/admin/partials/navbar.blade.php
Labels: Review effort 3/5, Possible security concern

#48 feat: Refactor AdminController and dashboard view; enhance ticket val…
  app/Http/Controllers/AdminController.php
  resources/views/admin/dashboard.blade.php
  resources/views/admin/partials/sidebar.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/admin/users/updateUsers.blade.php
  resources/views/emails/verify-email.blade.php
  routes/web.php
Labels: Review effort 2/5

#51 Implement soft delete functionality for events and update deletion co…
  app/Http/Controllers/EventController.php
  resources/views/admin/events/index.blade.php
Labels: Review effort 2/5

#53 NEW PUSH
  public/css/preview.css
  resources/views/admin/events/updateEvents.blade.php
  resources/views/auth/signup.blade.php
  resources/views/components/event_section.blade.php
Labels: Review effort 3/5

#55 New push
  app/Http/Controllers/EventController.php
  app/Http/Controllers/UserController.php
  public/css/app.css
  public/js/app.js
  resources/views/admin/events/createEvents.blade.php
  resources/views/admin/events/updateEvents.blade.php
  resources/views/components/event_section.blade.php
  resources/views/partials/header.blade.php
  resources/views/profile.blade.php
  resources/views/search_results.blade.php
  resources/views/user/searchevents.blade.php
  routes/web.php
Labels: Review effort 4/5, Possible security concern

#57 Enhance event management and navigation
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/CartController.php
  app/Http/Controllers/EventController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/TicketController.php
  app/Models/Payment.php
  app/Models/Ticket.php
  config/app.php
  public/css/event_section.css
  resources/views/admin/events/index.blade.php
  resources/views/admin/tickets/index.blade.php
  resources/views/components/event_section.blade.php
  resources/views/partials/header.blade.php
  routes/web.php
Labels: Review effort 4/5

#59 Add styling for eSewa payment method in tickets index
  resources/views/admin/tickets/index.blade.php
Labels: Review effort 1/5

#61 Dev
  resources/views/admin/tickets/index.blade.php
  resources/views/user/tickets/show.blade.php
Labels: Review effort 1/5

#63 Implement ticket payment total calculation and status update function…
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/HomeController.php
  resources/views/admin/tickets/index.blade.php
  routes/web.php
Labels: Review effort 3/5
